[package]
name = "initializer"
version = "0.1.0"
edition = "2021"

[lib]
name = "initializer"

[dependencies]
schema = { path = "../schema" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
